title:              CJ Blog
email:              sene.5s9horizons@gmail.com
description:        I wonder how far I can think before losing myself into the absoluteness of infinity
author:             pSeudo man
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://5s9horizons.github.io"

# Social Profiles
twitter_username:   5s9horizons
github_username:    5s9horizons
facebook_username:  5s9horizons
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
